/*

 @name    : 锅巴汉化 - Web汉化插件
 @author  : 麦子、JAR、小蓝、好阳光的小锅巴
 @version : V0.6.1 - 2019-07-09
 @website : http://www.g8hh.com
 @idle games : http://www.gityx.com
 @QQ Group : 627141737

*/

//1.汉化杂项
var cnItems = {
    _OTHER_: [],

    //未分类：
    'Save': '保存',
    'Export': '导出',
    'Import': '导入',
    'Settings': '设置',
    'Achievements': '成就',
    'Statistics': '统计',
    'Changelog': '更新日志',
    'Hotkeys': '快捷键',
    'ALL': '全部',
    'Default': '默认',
    'AUTO': '自动',
    'default': '默认',
    "points": "点数",
    "Reset for +": "重置得到 + ",
    "Currently": "当前",
    "Effect": "效果",
    "Cost": "成本",
    "Goal:": "目标:",
    "Reward": "奖励",
    "Start": "开始",
    "Exit Early": "提前退出",
    "Finish": "完成",
    "Milestone Gotten!": "获得里程碑！",
    "Milestones": "里程碑",
    "Completed": "已完成",
    "Default Save": "默认存档",
    "Delete": "删除",
    "No": "否",
    "Saves": "存档",
    "Options": "选项",
    "Yes": "是",
    "Are you sure?": "你确定吗？",
    "Edit Name": "编辑名称",
    "Info": "信息",
    "Currently:": "当前:",
    "Appearance": "外观",
    "How the game looks.": "游戏看起来如何。",
    "Theme": "主题",
    "Show milestones": "显示里程碑",
    "Show TPS meter at the bottom-left corner of the page.": "在页面左下角显示 TPS。",
    "Show TPS": "显示 TPS",
    "None": "无",
    "Align modifier units": "对齐概览单位",
    "Align numbers to the beginning of the unit in modifier view.": "在概览视图中将数字与单元的开头对齐。",
    "Select which milestones to display based on criterias.": "根据标准选择要显示的里程碑。",
    "All": "全部",
    "Classic": "经典",
    "Configurable": "可配置",
    "Duplicate": "复制",
    "Mute": "静音",
    "Unmute": "播放",
    "Join the Discord!": "加入 Discord!",
    "Fix export button and save": "修复导出按钮和保存",
    "ENABLED": "启用",
    "Export to file": "导出为文件",
    "Import clipboard": "从剪贴板导入",
    "Import file": "从文件导入",
    "DISABLED": "禁用",
    "Experience": "经验值",
    "Volume:": "音量:",
    "Update:": "更新:",
    "Time Limit:": "时间限制:",
    "Welcome to the Official Release!": "欢迎来到正式发布版本！",
    "UPGRADES": "升级",
    "Used:": "已使用:",
    "You cannot level up until this boss is defeated!": "在打败这个Boss之前，你不能升级！",
    "Equipped:": "已装备:",
    "Lasers:": "激光:",
    "BUY": "购买",
    "Buy Quantity:": "购买数量:",
    "Current:": "当前:",
    "Combat": "战斗",
    "Cosmic Fleet": "宇宙舰队",
    "English": "英语",
    "Owned": "已拥有",
    "Render:": "雷达:",
    "Speed Boost": "速度提升",
    "Ships:": "飞船:",
    "Sound Enabled:": "启用声音:",
    "Sound Settings": "声音设置",
    "Special Thanks": "特殊感谢",
    "The boss escaped!": "Boss逃跑了！",
    "Time Limit": "时间限制",
    "Threat Level": "威胁等级",
    "Reset Game": "重置游戏",
    "Reset Save": "重置保存",
    "Retry Boss": "重试Boss",
    "Set Points": "设置点数",
    "⚔️ Combat": "⚔️ 战斗",
    "⚙️ Settings": "⚙️ 设置",
    "✨ Artifacts": "✨ 神器",
    "✓ Statistics": "✓ 统计",
    "✓ Prestige Upgrades": "✓ 声望升级",
    "✓ Achievements": "✓ 成就",
    "⭐ Level & XP": "⭐ 等级 & 经验值",
    "🌟 ASCENSION 🌟": "🌟 转生 🌟",
    "Artifacts": "神器",
    "Ascend": "转生",
    "ASCEND NOW": "立即转生",
    "Available": "可用",
    "Background": "背景",
    "Background Music:": "背景音乐:",
    "Close": "关闭",
    "💬 Join Discord": "💬 加入Discord",
    "💰 Resources": "💰 资源",
    "👑 Mastery": "👑 精通",
    "Ships": "飞船",
    "Size": "尺寸",
    "⚡ Performance Monitor": "⚡ 性能监视器",
    "⚡ Power-Ups": "⚡ 通电",
    "⭐ Follow on GitHub": "⭐ 在GitHub关注",
    "🎨 Visual Customization": "🎨 可视化定制",
    "🎮 Credits & Share": "🎮 鸣谢&分享",
    "🎮 Game Controls": "🎮 游戏控制",
    "🎮 Steam Release": "🎮 Steam发布",
    "🎯 Missions & Quests": "🎯 任务与冒险",
    "🏆 Achievements": "🏆 成就",
    "🐦 Share on Twitter (X)": "🐦 在Twitter上分享(X)",
    "👾 Boss Controls": "👾 Boss控制",
    "💙 Wishlist on Steam - Coming Soon!": "💙 Steam上的愿望清单-即将推出！",
    "💥 BOBBLE": "💥 泡泡",
    "💻 Development": "💻 开发",
    "💾 Save Data Management": "💾 保存数据管理",
    "📈 Progression": "📈 进展",
    "📊 Game Information & Mechanics": "📊 游戏信息和机制",
    "📊 Statistics": "📊 统计",
    "📊 Stats": "📊 统计数据",
    "📢 Share Your Progress": "📢 分享你的进度",
    "📤 Import Save Data": "📤 导入保存数据",
    "📥 Export Save Data": "📥 导出保存数据",
    "📦 Collection": "📦 收藏",
    "🔒 Secret": "🔒 秘密",
    "🤖 Auto-Buy": "🤖 自动购买",
    "🚀 Fleet & Upgrades": "🚀 舰队与升级",
    "🚀 SOON": "🚀 敬请期待",
    "🚀 Starship Fleet": "🚀 星际舰队",
    "🛒 Shop": "🛒 商店",
    "🛠️ Admin Debug Panel": "🛠️ 管理员调试面板",
    "A massive alien entity blocks your progress!": "一个巨大的外星实体阻碍了你的进程！",
    "Alien Threat Detected": "侦测到外星威胁",
    "Ascend to a higher plane of existence. You will lose all progress except:": "转生到一个更高的存在层面。你将失去所有进度，除了：",
    "Auto-Buy: LOCKED - Purchase in Ascension Store for 50 Ascension Points": "自动购买：未解锁 - 在提转生商店花 50 转生点购买",
    "Backup your progress or transfer it between devices": "备份您的进度或在设备之间传输",
    "Be the first to know when BOBBLE launches on Steam!": "当《BOBBLE》在Steam上发行时，第一个知道！",
    "BOSS ENCOUNTER": "遭遇Boss",
    "Built with TypeScript, HTML5 Canvas, and lots of ☕": "使用TypeScript， HTML5 Canvas和大量☕构建",
    "Burning red and orange ships. Defeat 10 bosses to unlock.": "燃烧着红色和橙色的船。击败10个boss解锁",
    "Change the game language": "更改游戏语言",
    "Check out more projects and follow for updates!": "查看更多项目并关注更新！",
    "Classic Fleet": "经典的舰队",
    "Clear All Power-Ups": "完成所有通电",
    "Critical Surge": "暴击狂热",
    "Customize": "定制",
    "Daily Missions": "每日任务",
    "Damage #s:": "伤害 #s：",
    "Damage Boost": "伤害提升",
    "Damage Numbers:": "伤害数字:",
    "Defeat 10 bosses": "击败10个boss",
    "Disable particles for better performance": "禁用粒子以获得更好的性能",
    "Disable to improve performance (damage still applies)": "禁用以提高性能（伤害仍然适用）",
    "Disable to reduce lag (only your clicks will fire lasers)": "禁用以减少延迟（只有你的点击会发射激光）",
    "Enable or disable all game sounds": "启用或禁用所有游戏声音",
    "Enable or disable background music": "启用或禁用背景音乐",
    "ENGAGE BOSS": "与首领交战",
    "Entity Counts": "实体数量",
    "Español": "西班牙语",
    "EXTREME": "极端",
    "FPS:": "帧:",
    "Frame Time:": "帧时间:",
    "Gain on Ascension:": "转生收获：",
    "Game Design & Development": "游戏设计与开发",
    "Game Info": "游戏信息",
    "Ghostly blue ships with holographic effects. Reach level 100.": "带有全息效果的幽灵般的蓝色飞船。达到100级。",
    "Graphics Settings": "图形设置",
    "High Graphics (Particles):": "高级图形（粒子）：",
    "Hologram Fleet": "全息舰队",
    "Inferno Fleet": "地狱舰队",
    "Instant Kill Boss": "瞬间击杀Boss",
    "Language Settings": "语言设置",
    "Language:": "语言:",
    "Lasers": "激光",
    "Limit:": "上限：",
    "MAX": "最大",
    "Max All Basic Upgrades": "最大所有基本升级",
    "Max Current XP": "最大当前经验值",
    "Max Ships (50)": "最大船舶（50艘）",
    "Mechanics": "机制",
    "Memory": "内存",
    "Missions": "任务",
    "Multishot": "多重射击",
    "Mysterious purple ships with cosmic energy. Prestige level 3 required.": "带有宇宙能量的神秘紫色飞船。需要3级声望。",
    "Neon Fleet": "霓虹舰队",
    "Normal Speed": "正常速度",
    "Particles": "粒子",
    "Particles:": "粒子:",
    "Points Boost": "点数提升",
    "Pop bubblewrap aliens in the ultimate fake invasion! These bubblewrap creatures are \"threatening\" your profit margins - pop them all!": "在最终的假入侵中弹出泡泡袋外星人！这些泡泡糖生物正在“威胁”你的利润——把它们都打碎吧！",
    "Português": "葡萄牙语",
    "Press": "新闻",
    "Prestige Upgrades": "声望升级",
    "Progression": "进度",
    "Purchase in Ascension Store (50 PP)": "在转生商店购买（50 声望点数）",
    "Recruit another starship to your armada. Each ship fires independently, adding to your total DPS. More ships = more simultaneous attacks!": "招募另一艘星舰加入你的舰队。每艘船独立开火，增加你的总DPS。更多的船=更多的同时攻击！",
    "Regular Missions": "日常任务",
    "Retry the boss fight. Shows the boss dialog again to restart the encounter.": "重试boss战。再次显示boss对话框以重新开始遭遇战。",
    "Set Level": "设置等级",
    "Share your stats and achievements with your friends!": "与你的朋友分享你的统计数据和成就！",
    "Ship Auto-Fire Lasers:": "船舶自动发射激光：",
    "The standard white ships. Clean and reliable.": "标准的白色船只。清洁可靠。",
    "TIME'S UP!": "时间到了！",
    "Tips": "提示",
    "To all players and the incremental games community!": "致所有玩家和增量游戏社区！",
    "to toggle": "切换",
    "to toggle this panel": "来切换这个面板",
    "Toggle God Mode": "切换神模式",
    "Total:": "总计：",
    "Trigger Boss Fight": "触发Boss战",
    "UNDERSTOOD": "明白了",
    "Unlock All Special Upgrades": "解锁所有特殊升级",
    "Vibrant cyan ships with neon glow. Unlocked at level 25.": "充满活力的青色船与霓虹辉光。25级时解锁。",
    "You must defeat it to progress.": "你必须打败它才能进步。",
    "You will gain Prestige Points to unlock permanent bonuses!": "您将获得声望点解锁永久加成！",
    "Achievement Unlocked!": "成就已解锁！",
    "Fleet Commander": "舰队指挥官",
    "No special upgrades owned yet.": "暂未拥有特殊升级，",
    "Recruit your first additional ship": "招募你的第一艘飞船",
    "Reach level 1000 - You are limitless!": "升到1000级 - 你是无限！",
    "⚡ Attack Speed": "⚡攻击速度",
    "Critical Surge": "暴击狂热",
    "Damage Boost": "伤害提升",
    "Multishot": "多重射击",
    "✨ Critical Strike": "✨ 暴击",
    "🏭 Passive Income": "🏭 被动收入",
    "💎 Damage Amplifier": "💎 伤害放大器",
    "📚 Knowledge Core": "📚 知识核心",
    "Automated alien elimination stations. They generate Points (currency) continuously while you play. Very efficient defense system.": "自动外星人消灭站。它们会在你玩游戏时不断生成点数（货币）。非常有效的防御系统。",
    "Destroy your first alien": "摧毁你的第一个外星人",
    "Enhance laser power for maximum destruction per hit.": "增强激光威力，使每次攻击的破坏力达到最大。",
    "First Blood": "第一滴血",
    "Land your first critical hit": "打出你的第一个暴击",
    "Learn advanced alien elimination techniques. Knowledge is power. Especially when eliminating.": "学习先进的外星人消灭技术。知识就是力量。尤其是在消除的时候。",
    "Lucky Shot": "幸运射击",
    "Master the perfect critical hit. Maximum destruction efficiency. Very satisfying.": "掌握完美的暴击。最大的破坏效率。非常令人满意的。",
    "Upgrade targeting computers to fire faster. Speed is everything.": "升级瞄准电脑，提高射击速度。速度就是一切。",
    "Addicted": "上瘾",
    "Alien Annihilator": "外星人歼灭者",
    "Alien Apocalypse": "外星人启示录",
    "Alien Destroyer": "外星人驱逐舰",
    "Alien Extinction": "外星人灭绝",
    "Alien Hunter": "外星人猎人",
    "Alien Slayer": "外星人杀手",
    "Apprentice": "学徒",
    "Armada": "无敌舰队",
    "Ascended": "转生",
    "Balanced": "平衡",
    "Billionaire": "亿万富翁",
    "Black Hole": "黑洞",
    "Boss Annihilator": "Boss歼灭者",
    "Boss God": "Boss之神",
    "Boss Hunter": "Boss猎人",
    "Boss Legend": "Boss传说",
    "Boss Master": "Boss大师",
    "Boss Obliterator": "Boss毁灭器",
    "Boss Slayer": "Boss杀手",
    "Caffeine Addict": "咖啡因成瘾",
    "Champion": "冠军",
    "Click an alien for the first time": "第一次点击外星人",
    "Click God": "点击之神",
    "Click Legend": "单击传奇",
    "Click Maniac": "点击狂人",
    "Click Master": "点击大师",
    "Committed": "承诺",
    "Cosmic Ascension": "宇宙转生",
    "Cosmic Damage": "宇宙伤害",
    "Cosmic Energy Master": "宇宙能量大师",
    "COSMIC GOD": "宇宙之神",
    "Cosmic Voyager": "宇宙航行者",
    "Crit Hunter": "暴击猎人",
    "Crit Legend": "暴击传说",
    "Crit Master": "暴击大师",
    "Crit Specialist": "暴击专家",
    "Critical God": "暴击之神",
    "Critical Storm": "暴击风暴",
    "Damage Dealer": "伤害经销商",
    "Damage Deity": "伤害之神",
    "Damage Emperor": "伤害皇帝",
    "Damage King": "伤害之王",
    "Damage Master": "伤害大师",
    "Damage Overlord": "损害霸王",
    "Dark Matter Harvester": "暗物质收割机",
    "Dedicated": "专用",
    "Defeat your first boss": "击败你的第一个boss",
    "Demigod": "半神",
    "Destroy your first alien": "摧毁你的第一个外星人",
    "Dimension Breaker": "尺寸破碎机",
    "Dragon Tamer": "驯龙师",
    "Elite": "精英",
    "Entrepreneur": "企业家",
    "Expert": "专家",
    "First Blood": "第一滴血",
    "First Contact": "第一次接触",
    "Galactic Empire": "银河帝国",
    "Galaxy Conqueror": "银河征服者",
    "Getting Started": "入门",
    "Grandmaster": "特级大师",
    "Hidden achievement": "隐藏成就",
    "Hyper-Dimensional": "超维度",
    "Immortal": "不朽的",
    "Innovator": "创新者",
    "Journeyman": "熟练工人",
    "Knowledge Deity": "知识之神",
    "Land your first critical hit": "打出你的第一个暴击",
    "Legendary": "传说",
    "Light Speed Master": "光速大师",
    "Lucky Shot": "幸运射击",
    "Magnate": "大亨",
    "Master": "大师",
    "Master of Illusion": "幻术大师",
    "Mega Fleet Commander": "巨型舰队指挥官",
    "Millionaire": "百万富翁",
    "Nanotech Engineer": "纳米技术工程师",
    "Nebula Harvester": "星云收割机",
    "Nebula Master": "星云大师",
    "No Life": "无生命",
    "Novice": "新手",
    "Obsessed": "痴迷",
    "Omnipotent Destroyer": "全能破坏者",
    "Passive Master": "被动大师",
    "Passive Overlord": "被动霸王",
    "Patience is a Virtue": "忍耐是美德",
    "Perfectly Balanced": "完美平衡",
    "Plasma Master": "等离子大师",
    "Purchase your first upgrade": "购买第一次升级",
    "Quantum Physicist": "量子物理学家",
    "Reality Bender": "现实扭曲",
    "Researcher": "研究员",
    "Scholar": "学者",
    "Singularity": "奇点",
    "Small Fleet": "小舰队",
    "Space Force": "空间力量",
    "Speed Demon": "速度之魔",
    "Speed God": "速度之神",
    "Starter Capital": "启动资本",
    "Stellar Champion": "恒星冠军",
    "Stellar Engineer": "恒星工程师",
    "Super Rich": "超级富豪",
    "Supernova": "超新星",
    "Supreme Armada": "无敌舰队",
    "Tech Collector": "科技收集器",
    "Tech Legend": "科技传奇",
    "Tech Master": "科技大师",
    "Technology God": "科技之神",
    "The Meaning of Life": "生命的意义",
    "Time Lord": "时间领主",
    "Titan": "泰坦",
    "Transcendent": "卓越",
    "Transcendent Clicker": "卓越点击器",
    "Tycoon": "大亨",
    "Ultimate Power": "最高权力",
    "Ultra Rich": "超级富豪",
    "Ultra Speed": "极速",
    "Universal Force": "万能之力",
    "Universe Destroyer": "宇宙毁灭者",
    "Unlock all special technologies": "解锁所有特殊技术",
    "Unlock Cosmic Energy Battery": "解锁宇宙能量电池",
    "Unlock Dark Matter Engine": "解锁暗物质引擎",
    "Unlock Holographic Decoy System": "解锁全息诱饵系统",
    "Unlock Hyper-Dimensional Reactor": "解锁超维度反应堆",
    "Unlock Nebula Energy Harvester": "解锁星云能量采集器",
    "Unlock Photon Wave Amplifier": "解锁光子波放大器",
    "Unlock Quantum Entanglement Core": "解锁量子纠缠核心",
    "Unlock Reality Anchor": "解锁现实锚",
    "Unlock Self-Replicating Nanobots": "解锁自我复制的纳米机器人",
    "Unlock Stellar Forge": "解锁恒星锻造",
    "Unlock Temporal Acceleration Field": "解锁时间加速场",
    "Unlock the Answer to Everything": "解开所有问题的答案",
    "Unlock the Cosmic Ascension Protocol": "解锁宇宙转生协议",
    "Unlock the Crew Coffee Machine": "解锁船员咖啡机",
    "Unlock the Dragon Egg": "解锁龙蛋",
    "Unlock the Infinity Gauntlet (Replica)": "解锁无限手套（副本）",
    "Unlock the Meaning of Life upgrade": "解锁“人生意义”升级",
    "Unlock the Plasma Energy Matrix": "解锁等离子能量矩阵",
    "Unlock the Singularity Power Core": "解锁奇点能量核心",
    "Unlock your first special technology": "解锁你的第一个特殊技术",
    "Upgrade Deity": "升级之神",
    "Upgrade Enthusiast": "升级爱好者",
    "Upgrade Legend": "升级传说",
    "Upgrade Master": "升级大师",
    "Veteran": "老兵",
    "Wait without clicking for 30 seconds": "等待30秒，不要点击",
    "Wealthy": "富有",
    "Well Rounded": "全面发展",
    "- it affects everything!": "- 它影响一切！",
    "(they're permanent!)": "（它们是永久的！）",
    "(XP) helps you level faster": "（经验）帮助你更快升级",
    "Alien Hunter": "外星猎手",
    "Combo Master": "连击大师",
    "Level Up": "升级",
    "• Ascend at level 100+ to gain": "• 升到100级以上就可以获得",
    "• Balance between damage upgrades and cost reduction": "• 平衡伤害升级和成本降低",
    "• Boss HP scales with level and has a time limit": "• Boss的血量随等级而变化，并且有时间限制",
    "• Bosses appear at": "• boss出现在",
    "• Build combo by hitting enemies without a 5-second gap": "• 在不间隔5秒的情况下击中敌人，创造连击",
    "• Collect all Special Upgrades for maximum power": "• 收集所有特殊升级以获得最大能量",
    "• Combo resets if you don't hit anything for 5 seconds": "• 如果你在5秒内没有击中任何东西，连击会重置",
    "• Damage multiplier:": "•伤害乘数：",
    "• Defeating bosses gives": "•打败boss",
    "• Don't neglect": "•不要忽视",
    "• Example: 100 combo = 1.1x damage, 1000 combo = 2x damage": "• 例子：100连击= 1.1倍伤害，1000连击= 2倍伤害",
    "• Focus on": "•专注于",
    "• Having 75% of the cost (technology becomes visible)": "• 拥有75%的成本（技术变得可见）",
    "• If you fail, you can retry with better upgrades": "• 如果你失败了，你可以用更好的升级重试",
    "• Invest in": "•投资于",
    "• Meeting level requirements for the base upgrade": "• 满足基础升级的等级要求",
    "• Prestige upgrades provide permanent multiplicative bonuses": "• 声望升级提供永久的倍增奖励",
    "• Purchasing with accumulated points": "• 用累积点数购买",
    "• Push for higher levels before ascending for more PP": "• 在转生之前推动更高的级别以获得更多的声望点数",
    "• Start buying": "• 开始购买",
    "• Upgrade": "• 升级",
    "⌨️ Keyboard Shortcuts": "⌨️ 键盘快捷键",
    "⚔️ Combat Stats": "⚔️ 战斗统计",
    "⚔️ Your Damage Output": "⚔️ 你的伤害输出",
    "⚙️ How Upgrades Affect You": "⚙️ 升级如何影响你",
    "⚠️ \"Boost All Systems\" upgrades increase damage and fleet power, NOT passive generation!": "⚠️ \“提升所有系统\”升级增加伤害和舰队动力，而不是被动发电！",
    "⚠️ Special Upgrades are LOST on ascension - buy them again with your prestige bonuses!": "⚠️ 特殊升级在提升中丢失-用您的声望加成再次购买！",
    "⚠️ You LOSE all special upgrades, regular upgrades, levels, and currency": "⚠️ 你将失去所有特殊升级，常规升级，关卡和货币",
    "✓ Claimed": "✓ 已领取",
    "✨ Critical Hits": "✨ 暴击",
    "⭐ Late Game (100+)": "⭐ 后期游戏（100+）",
    "⭐ SPECIAL UPGRADES ⭐": "⭐ 特殊升级 ⭐",
    "🌌 Cosmic Knowledge:": "🌌 宇宙知识：",
    "🌟 Ascension System": "🌟 转生系统",
    "🎯 Accuracy Info": "🎯 精准信息",
    "🎯 Early Game (Levels 1-30)": "🎯 早期游戏（1-30级）",
    "👾 Boss Encounters": "👾 Boss遭遇战",
    "👾 Enemy Types": "👾 敌人类型",
    "💎 Cost Reduction Systems": "💎 降低成本系统",
    "💡 Critical hits work on both your clicks AND your fleet's automatic shots!": "💡关键打击工作在你的点击和你的车队的自动射击！",
    "💡 Prestige Points are earned for each NEW level beyond your previous best": "💡声望点是赢得每一个新的水平超过你以前的最好",
    "💡 Pro Tips": "💡专业提示",
    "💡 These stack multiplicatively with Special Upgrade discounts!": "💡这些叠加与特殊升级折扣！",
    "💡 You gain 1 XP per enemy killed. Boss enemies give 10x XP!": "💡每杀死一个敌人，你将获得1点经验值。Boss敌人给予10倍经验值！",
    "💰 Income Sources": "💰 收入来源",
    "💰 Wealth Stats": "💰 财富统计",
    "📈 Leveling System": "📈 升级系统",
    "📈 Progression Stats": "📈 进度统计",
    "📊 Special Technology Progress": "📊 特殊科技进度",
    "🔄 Combo System": "🔄 连击系统",
    "🔬 Technology Stats": "🔬 技术统计",
    "🔴 Tank (15%, Lv 20+):": "🔴 坦克（15%, 等级 20+）：",
    "🚀 Fleet Command:": "🚀 舰队指挥部：",
    "🚀 Mid Game (Levels 30-100)": "🚀 游戏中期（30-100级）",
    "🛸 Fleet Stats": "🛸 舰队统计",
    "🟡 Scout (20%, Lv 10+):": "🟡 侦察兵（20%,Lv 10+）：",
    "🟢 Healer (5%, Lv 30+):": "🟢 治疗者（5%,lv30 +）：",
    "🟢 Normal (60%):": "🟢 普通（60%）：",
    "Achieve a 10x combo": "完成10次连击",
    "Active Strategy:": "主动策略：",
    "Affects both clicks and fleet shots": "同时影响点击和舰队射击",
    "Aliens Killed": "击杀外星人",
    "and": "和",
    "and allows you to continue leveling": "并允许你继续升级",
    "Attack Speed": "攻击速度",
    "Attack Speed Level": "攻击速度等级",
    "Attack Speed:": "攻击速度:",
    "Boss Prep:": "Boss准备：",
    "Bosses Defeated": "击败boss",
    "Both click and fleet damage can crit for 1.1x damage": "点击和舰队伤害都可以造成1.1倍伤害的暴击",
    "Bulk Buy:": "批量购买:",
    "Can Ascend:": "可以转生:",
    "Claim": "领取",
    "Classic Particles": "经典粒子",
    "Classic Space": "经典空间",
    "Clean white lasers. Always available.": "干净的白色激光器。总是可用的。",
    "Click Damage (Main Ship):": "点击伤害（主舰）：",
    "Close any open modal": "关闭任何打开的模态框",
    "Colorful nebula clouds and vibrant stars. Reach level 75.": "五颜六色的星云云和充满活力的恒星。达到75级",
    "Colorful rainbow lasers. Unlocked at level 50.": "彩色彩虹激光器。50级解锁。",
    "Combo System:": "合击系统：",
    "Cosmic Knowledge": "宇宙知识",
    "Crit Chance": "暴击几率",
    "Crit Chance:": "暴击几率：",
    "Crit Damage (Main Ship):": "暴击伤害（主舰）：",
    "Crit Level": "暴击等级",
    "Crit Multiplier:": "暴击乘数:",
    "Critical Hits": "暴击",
    "Critical Hits:": "暴击：",
    "Current Level": "当前等级",
    "Current Level:": "当前等级:",
    "Current Points": "当前点",
    "Damage": "伤害",
    "Damage Level": "伤害等级",
    "Damage Per Ship:": "单船伤害：",
    "Damage:": "伤害:",
    "Dark energy from the void. Prestige level 5.": "来自虚空的暗能量。声望等级5。",
    "Dark void with subtle stars. Defeat 50 bosses.": "暗无天日，繁星点点。击败50个boss",
    "Deal 5,000 damage": "造成5000点伤害",
    "Death Pact Agreement": "死亡契约",
    "Each ship adds to your total DPS": "每艘船都会增加你的总DPS",
    "Energy Reactor": "能量反应堆",
    "Energy Reactor:": "能量反应堆:",
    "ESC:": "ESC:",
    "Fleet Attack Speed:": "舰队攻击速度：",
    "Fleet Ships:": "舰队:",
    "Focus on click damage and crit chance": "专注于点击伤害和暴击几率",
    "for consistent DPS": "为了一致的每秒伤害(DPS)",
    "Glowing Particles": "发光粒子",
    "Golden sparkles on hits. Unlocked at level 30.": "金光闪闪。30级解锁。",
    "Hot plasma energy beams. Defeat 25 bosses.": "热等离子体能量束。打败25个boss",
    "How fast your fleet fires (does NOT affect your clicks)": "你的舰队开火有多快（不影响你的点击）",
    "Idle Strategy:": "放置策略：",
    "Increases both click AND fleet damage": "增加点击和舰队伤害",
    "Keep attacking for damage multipliers!": "继续攻击以增加伤害！",
    "Knowledge Core": "知识核心",
    "Knowledge Core:": "知识核心：",
    "Long-lasting particle trails. Prestige level 2.": "持久的粒子轨迹。声望等级2。",
    "Luminous particles with glow effects. Defeat 15 bosses.": "具有发光效果的发光粒子。击败15个boss",
    "Main Ship (Clicks):": "主船（点击）：",
    "Max Level Reached": "达到最高等级",
    "Max out Energy Reactor for offline gains": "使能量反应堆的离线增益达到最大值",
    "Nebula Sky": "星云天空",
    "No (reach level 100)": "否（达到100级）",
    "No artifacts equipped": "没有装备神器",
    "No artifacts found. Complete missions and bosses to earn artifacts!": "没有发现神器。完成任务和boss获得神器！",
    "Open Achievements": "开启成就",
    "Open Game Info": "打开游戏信息",
    "Open Missions": "开启任务",
    "Open Prestige/Ascension": "开启声望/转生",
    "Open Settings": "打开设置",
    "Passive Gen Level": "被动生成等级",
    "Passive Generation:": "被动生成:",
    "Passive points per second (offline progress)": "每秒被动点数（离线进度）",
    "Per Hour:": "每小时:",
    "Plasma Stream": "等离子流",
    "Play Time": "游戏时间",
    "PP On Ascension:": "转生获得声望点：",
    "Prestige Points": "声望点数",
    "provides passive income for when you're away": "当你不在的时候提供被动收入",
    "Rainbow Beam": "彩虹光束",
    "regular intervals": "定期间隔",
    "Ships gain +10% attack speed": "舰船增加10%攻击速度",
    "Signed contract guarantees \"hostile\" alien supply chain. Very convenient.": "签署的合同保证“敌对”的外星人供应链。非常方便。",
    "Sparkle Effect": "闪光效果",
    "Special Technologies": "特殊科技",
    "Special Upgrades": "特殊升级",
    "Standard Beams": "标准光束",
    "Standard HP, standard rewards": "标准生命值，标准奖励",
    "Standard white particles. Always available.": "标准的白色粒子。随时可用。",
    "Tech Enthusiast": "科技爱好者",
    "Technology Progress": "科技进度",
    "The original starfield background. Always available.": "原始的星域背景。总是可用的。",
    "To increase passive income, upgrade the \"🏭 Energy Reactor\" system.": "为了增加被动收入，升级“🏭能源反应堆”系统。",
    "to reduce all costs": "降低所有成本",
    "to scale both clicks and fleet power": "以同时提升点击率和舰队力量",
    "Toggle Auto-Buy": "切换自动购买",
    "Toggle Debug Panel (cheat mode)": "",
    // "Toggle Debug Panel (cheat mode)": "切换调试面板（作弊模式）",
    "Toggle Performance Monitor": "切换性能监视器",
    "Total Clicks": "总点击",
    "Total Damage": "总伤害",
    "Total Experience": "总经验",
    "Total Fleet DPS:": "舰队总每秒伤害（DPS）：",
    "Total Points Earned": "累计获得点数",
    "Total Upgrades Purchased": "购买的总升级",
    "Trail Effect": "跟踪效果",
    "Unlock Special Technologies by:": "解锁特殊技术：",
    "Upgrade before boss fights (every 25+ levels)": "boss战前升级（每25级以上）",
    "Use the buy quantity selector (1, 5, 10, MAX)": "使用购买数量选择器（1,5,10，MAX）",
    "Void Beam": "虚空光束",
    "Void Realm": "虚空领域",
    "XP Boost Level": "经验加成等级",
    "XP gain multiplier for faster leveling": "经验值增益乘数对于更快的升级",
    "XP Multiplier:": "经验值乘数:",
    "XP Progress:": "经验进度：",
    "You keep: Achievements, Statistics, and Prestige Upgrades ONLY": "你只保留：成就、统计数据和声望升级",
    "Crew Coffee Machine": "船员咖啡机",
    "Crew stays awake for 24/7 defense operations. The aliens are coming. Definitely coming.": "船员们24小时不睡觉进行防御行动。外星人来了。绝对的到来。",
    "✓ OWNED": "✓ 已拥有",
    "🔥 Weapon Mastery": "🔥 武器精通",
    "Master the art of destruction - increase main ship firepower": "精通毁灭之术 - 增加主舰火力",
    "⚡ Energy Core": "⚡ 能量核心",
    "Harness pure energy - boost all systems": "利用纯净的能量 - 提升所有系统",
    "All upgrades are 5% cheaper": "所有升级都便宜5%",
    "Each ship fires 0.12 times per second, dealing 2 per hit": "每艘船每秒发射0.12次，每次击中造成2点伤害",
    "Energy Recycling System": "能源回收系统",
    "Recycle alien material for maximum efficiency. Very environmentally conscious defense operation.": "回收外星材料，以达到最高效率。非常环保的防御行动。",
    "🌌 Cosmic Knowledge": "🌌 宇宙知识",
    "🧬 Mutation Engine": "🧬 突变引擎",
    "🛸 Fleet Command": "🛸 舰队指挥部",
    "Command your fleet with precision - boosts all ships' effectiveness and reduces ship upgrade costs": "精确指挥你的舰队——提高所有船只的效率，降低船只升级成本",
    "Evolve beyond limits - unlock transformative abilities": "超越极限的进化-解锁变革能力",
    "Fleet coordinates synchronized attacks. The aliens never stand a chance. Especially these ones.": "舰队坐标同步攻击。外星人根本没有机会。尤其是这些。",
    "Ships coordinate attacks for +20% damage": "船只协同攻击，造成+20%伤害",
    "Swarm Intelligence Protocol": "群智能协议",
    "Understand the universe - reduces ALL upgrade costs (including post-ascension prestige upgrades). Wisdom is power.": "了解宇宙-降低所有升级成本（包括转生后的声望升级）。智慧就是力量。",
    "+5% critical hit chance": "+5%暴击几率",
    "Increase point gain by 15%": "增加15%的点数增益",
    "Laser Focusing Crystals": "激光聚焦晶体",
    "Lucky Space Dice": "幸运太空骰子",
    "Precise targeting ensures maximum... elimination efficiency. The paperwork checks out.": "精确瞄准确保最大…消除效率。文件核对无误。",
    "Quantum Targeting Array": "量子瞄准阵列",
    "Rolled a 7! These dice ensure maximum alien destruction rates. The invasion pays... wait.": "掷出7！这些骰子确保最大的外星人毁灭率。入侵付出了代价……等待。",
    "Ships fire 20% faster": "舰船发射速度提高20%",
    "These crystals make the aliens make a very satisfying *pop* sound when destroyed.": "这些晶体使外星人在被摧毁时发出非常令人满意的“砰”声。",
    "+10% main ship damage": "+10%的主舰伤害",
    "+12% auto-fire damage": "+12%的自动射击伤害",
    "+5% all damage, adapts to enemy types": "+5%所有伤害，适应敌人类型",
    "+5% attack speed, +100/sec passive": "+5%攻击速度，+100/秒被动",
    "Adaptive Evolution": "适应性进化",
    "Ancient Texts": "古籍",
    "Clicking grants 10% bonus points": "点击可以获得10%的奖励点数",
    "Critical hits: 5% chance for 10x damage": "暴击：5%几率造成10倍伤害",
    "Drill Sergeant AI": "AI教官",
    "DROP AND GIVE ME TWENTY... MILLION DAMAGE!": "趴下，给我二十...百万伤害!",
    "Every shot finds its mark. Every. Single. One.": "每一枪都命中目标。每一个。单个。一个。",
    "Fusion Reactor": "聚变反应堆",
    "Gain 25% more points per hit": "每次命中增加25%的点数",
    "Measure twice, destroy once.": "测量两次，破坏一次。",
    "Neural link directly to your trigger finger. Click faster, eliminate faster. Very efficient.": "神经链直接连接到你的扳机手指。点击得越快，消除得越快。很能干的人。",
    "Neural Link Interface": "神经链路接口",
    "Overclock reactors beyond safety limits. Defense emergencies require... creative solutions.": "超频反应堆超出安全限制。国防紧急情况需要……创造性的解决方案。",
    "Overclocked Reactors": "超频反应堆",
    "Perfect Precision Arrays": "完美精度阵列",
    "Scope Calibration": "校准范围",
    "Survival of the fittest. You are the fittest.": "适者生存。你是最健康的。",
    "The power of the sun, in your hands.": "太阳的力量，掌握在你的手中。",
    "The wisdom of civilizations long dead.": "文明的智慧早已消亡。",
    "\"Hang in there!\" says the cat dangling from a satellite dish.": "“坚持住！”挂在卫星天线上的猫说。",
    "[DAILY] Alien Hunter": "[日常] 外星人猎人",
    "+1% critical damage multiplier": "+1%暴击伤害倍率",
    "+15% main ship damage, +5% click speed": "+15%主船伤害，+5%点击速度",
    "+18% auto-fire damage, ships move in formation": "+18%自动射击伤害，船只编队移动",
    "✅ 💰 Points Boost Activated!": "✅ 💰 点数提升激活！",
    "Access the universal library.": "访问通用库。",
    "Accidents happen. A lot.": "事故时有发生。很多。",
    "Akashic Records": "阿卡西记录",
    "Debugging Rubber Duck": "橡皮鸭调试",
    "Explains your problems back to you. Very therapeutic.": "向你解释你的问题。很好的治疗效果。",
    "Formation Delta": "编队三角洲",
    "Hair Trigger Mechanism": "毛发触发机制",
    "Intergalactic Pizza Delivery": "星际披萨外卖",
    "Keep crews fed during extended defense operations. Happy workers eliminate aliens better.": "在长时间的防御行动中，保证船员们吃饱。快乐的员工能更好地消灭外星人。",
    "Motivational Posters": "励志海报",
    "Points": "点数",
    "Unity is strength. And more damage.": "团结就是力量。还有更多的伤害。",
    "+20% main ship damage, +10% crit damage": "+20%主船伤害，+10%暴击伤害",
    "Aliens confused, +15% all stats": "迷惑外星人，全属性+15%",
    "Click with the power of a thousand suns. Or at least a few.": "点击一千个太阳的力量。或者至少有几个。",
    "Clicking gives +100% more points": "点击给+100%更多的点",
    "Critical hits deal 3% more damage": "暴击造成的伤害提高3%",
    "Hollow Point Rounds": "空心弹",
    "Hypnotic Disco Ball": "催眠迪斯科球",
    "Lucky Horseshoe": "幸运马蹄铁",
    "Master Clicker": "点击大师",
    "The aliens can't resist the disco beat. They line up perfectly for... elimination.": "外星人无法抗拒迪斯科的节奏。它们完美地排列在一起……消除。",
    "They expand on impact. So does your damage.": "他们扩大影响。你的损失也是如此。",
    "Who needs horses in space? Apparently, luck does.": "太空中谁需要马？显然，运气可以。",
    "Theoretical physics becomes practical firepower.": "理论物理变成了实用的火力。",
    "Experimental Warp Core": "实验扭曲核心",
    "Ships fire 50% faster": "舰船开火速度提高50%",
    "Antimatter Ammunition": "反物质弹药",
    "Antimatter makes the aliens pop twice as satisfyingly. Very therapeutic for stress relief.": "反物质使外星人的爆炸效果达到了两倍。对缓解压力很有治疗作用。",
    "Double all point gains": "所有点数增益翻倍",
    "+8% all damage, weapons evolve with use": "+8%所有伤害，武器随使用而进化",
    "+8% attack speed, +250/sec passive": "+8%攻击速度，+250/秒被动",
    "Both click and fleet damage can crit for 1.2x damage": "点击和舰队伤害都可以造成1.2倍伤害的暴击",
    "Harvest energy from the quantum foam.": "从量子泡沫中收集能量。",
    "Symbiotic Weapons": "共生武器",
    "Your weapons are alive. And hungry.": "你的武器是活的。而且很饿。",
    "Zero Point Energy": "零点能量",
    "+22% auto-fire damage, ships self-repair": "+22%自动火力伤害，船只自行修复",
    "Duct tape in space. It works!": "太空中的管道胶带。它奏效了！",
    "Emergency Repair Drones": "应急维修无人机",
    "[DAILY] Fleet Commander": "[每日] 舰队指挥官",
    "✅ ⚔️ Damage Boost Activated!": "✅ ⚔️ 伤害增强激活！",
    "AI Optimization Subroutines": "AI优化子程序",
    "ℹ️ 📅 New Daily Missions Available!": "ℹ️ 📅 新的每日任务！",
    "Ship fire cooldown reduced by 30%": "舰船火力冷却时间减少30%",
    "The AI promises it won't become self-aware. Probably.": "AI承诺不会成为自我意识。可能吧。",
    "+12% attack speed, +500/sec passive": "+12%攻击速度，+500/秒被动",
    "+30% main ship damage": "增加30%主船伤害",
    "All upgrades 20% cheaper": "所有升级都便宜20%",
    "Build a fleet of 12 ships": "建造一支有12艘船的舰队",
    "Cheat Code Manual": "作弊码手册",
    "Explosive Payload": "爆炸载荷",
    "Malfunctioning Time Machine": "时间机器故障",
    "Perfection": "完美",
    "Perpetual Motion Machine": "永动机",
    "Physics professors hate this one trick!": "物理教授讨厌这个把戏！",
    "Sets time forward, backward, and sideways. Results may vary.": "设置时间向前，向后和横向。结果可能会有所不同。",
    "Sometimes subtlety is overrated.": "有时候，微妙被高估了。",
    "Up, Up, Down, Down, Left, Right, Left, Right, B, A, Start.": "上，上，下，下，左，右，左，右，B， A，开始。",
    "[DAILY] Combo Master": "[每日]连击大师",
    "+25% auto-fire damage per 10 ships": "每10艘船增加25%的自动火力伤害",
    "Advanced Fleet Tactics": "高级舰队战术",
    "Coordination makes the dream work.": "协调使梦想成真。",
    "Destroying aliens grants bonus XP": "摧毁外星人可以获得额外的经验值",
    "The void stares back. It approves of your... efficient defense operations.": "虚空凝视着我。它赞成你的……有效的防御行动。",
    "Void Energy Channeling": "虚空能量通道",
    "All damage +35%": "所有伤害 +35%",
    "Gotta go fast! Wait, wrong franchise...": "得快点！等等，特许经营错了……",
    "Seven Chaos Emeralds": "七个混乱绿宝石",
    "+12% all damage, passive healing": "+12%所有伤害，被动治疗",
    "Damage? What damage?": "伤害? 什么伤害？",
    "Regenerative Hull": "再生船体",
    "-7% all costs, +20% XP, see the future": "-7%所有成本，+20%经验，预见未来",
    "": "",
    "Prophetic Vision": "先知异象",
    "You know what comes next.": "你知道接下来会发生什么。",
    "Technology Master V2": "科技大师 V2",
    "+15% attack speed, chain lightning": "+15%攻击速度，连锁闪电",
    "✅ ⚡ Speed Boost Activated!": "✅⚡速度提升激活！",
    "Holographic Decoy System": "全息诱饵系统",
    "One ship becomes many. Confusion intensifies.": "一艘船可以变成许多艘船。混乱加剧了。",
    "Ships can attack twice as often": "船只的攻击频率是它的两倍",
    "Speed": "速度",
    "Tesla Coils": "特斯拉线圈",
    "Unlimited power!": "无限动力！",
    "Self-Replicating Nanobots": "可以自我复制的纳米机器人",
    "They multiply. They evolve. They pay dividends.": "它们会相乘。它们在进化。他们支付股息。",
    "Plays Pac-Man while generating infinite energy. Science!": "一边吃豆人一边产生无限能量。科学!",
    "Retro Arcade Machine": "复古街机",
    "+18% all damage, shared consciousness": "+18%所有伤害，共享意识",
    "Hive Mind Connection": "蜂群思维连接",
    "Understand all languages. Even alien ones.": "了解所有语言。甚至是外星人。",
    "Universal Translator": "通用翻译器",
    "We are many. We are one.": "我们有很多。我们是一体。",
    "Critical hit chance +5%, Critical damage +3%": "暴击几率+5%，暴击伤害+3%",
    "Dragon Egg": "龙蛋",
    "It's either a dragon egg or a really angry space chicken.": "要么是龙蛋，要么是一只愤怒的太空鸡。",
    "✅ 💥 Critical Surge Activated!": "✅ 💥 暴击狂热已激活!",
    "Crit": "暴击",
    "+20% attack speed, +1000/sec passive": "+20%攻击速度，+1000/秒被动",
    "Arc Reactor": "弧形反应堆",
    "Proof that you have a heart. A mechanical one.": "证明你有一颗心。一个机械的。",
    "+50% main ship damage": "+50%的主舰伤害",
    "Accelerates particles. And destruction.": "加速粒子。还有毁灭。",
    "Particle Accelerator Cannon": "粒子加速器加农炮",
    "Critical hits +8%, Damage x1.5": "暴击+8%，伤害x1.5",
    "Quantum Entanglement Core": "量子纠缠核心",
    "Spooky action at a distance. Einstein hated it. You'll love it.": "幽灵般的超距作用。爱因斯坦讨厌它。你会喜欢的。",
    "Philosopher's Stone": "贤者之石",
    "Turns lead into gold. And boredom into... productivity. Very efficient.": "化铅为金。无聊变成…生产力。很能干的人。",
    "+35% auto-fire damage, reduced ship costs": "+35%的自动开火伤害，降低船的成本",
    "✅ ✨ Multishot Activated!": "✅✨多重射击激活！",
    "Automated Repair System": "自动修理系统",
    "Multi": "多重",
    "Ships that fix themselves. The future is now.": "能自我修复的船。未来就是现在。",
    "+25% all damage, immune to debuffs": "所有伤害+25%，免疫负面效果",
    "Perfect Organism": "完美的生物",
    "Perfection achieved. Evolution complete.": "完美实现。进化完成。",
    "🎉 BOSS DEFEATED! 🎉": "🎉Boss被打败了！🎉",
    "3, Ships +25% speed": "3、舰船速度+25%",
    "75%, All damage +20%": "75%，所有伤害+20%",
    "95% of the universe is dark matter. Now it's yours.": "95%的宇宙是暗物质。现在是你的了。",
    "All damage +25%, Attack speed +15%": "所有伤害+25%，攻速+15%",
    "All ships gain +100% attack speed": "所有舰船攻击速度+100%",
    "Dark Matter Engine": "暗物质引擎",
    "Each click fires 2 additional lasers": "每次点击发射2个额外的激光",
    "Harness the power of contained supernovas.": "利用内含超新星的能量。",
    "Plasma Energy Matrix": "等离子体能量矩阵",
    "Rapid Fire Protocol": "快速射击协议",
    "Stellar Forge": "恒星锻造",
    "Temporal Acceleration Field": "时间加速场",
    "Time is relative. Especially when you control it.": "时间是相对的。尤其是当你控制它的时候。",
    "Where stars are born, and enemies meet their end.": "在那里，星星诞生，敌人灭亡。",
    "Why fire one laser when you can fire three? Science!": "明明可以发射三个激光，为什么只发射一个？科学!",
    "Light speed is too slow. We're going to ludicrous speed!": "光速太慢了。我们要以荒唐的速度前进了！",
    "Photon Wave Amplifier": "光子波放大器",
    "Ships fire 75% faster, Damage +30%": "舰船开火速度提升75%，伤害+30%",
    "Critical damage +10%, All gains +25%": "暴击伤害+10%，所有增益+25%",
    "Keep reality in check. Or break it. Your choice.": "面对现实。或者打破它。你的选择。",
    "Reality Anchor": "现实锚定",
    "5000/sec, XP +50%": "5000/秒，经验值+50%",
    "All stats +40%": "所有属性+40%",
    "Almost all-knowing. Close enough.": "几乎无所不知。足够接近。",
    "Infinity Gauntlet (Replica)": "无限护手（复制品）",
    "Map of the Universe": "宇宙地图",
    "Nebula Energy Harvester": "星云能量采集器",
    "Omniscience Lite": "全知轻量版",
    "Perfectly balanced, as all things should be. Also, not trademarked.": "完美平衡，一切都应该如此。而且，没有商标。",
    "Siphon energy from the cosmic clouds themselves.": "从宇宙云中吸取能量。",
    "XP gain x3": "经验增益 x3",
    "You are here. So is everything else. Helpful!": "你在这里。其他的也一样。有用的!",
    "All damage x2, Critical chance +5%": "所有伤害x2，暴击几率+5%",
    "Fits in your pocket. Do not put in pocket.": "可以放在你的口袋里。不要放在口袋里。",
    "Hyper-Dimensional Reactor": "超维反应堆",
    "Pocket Nuclear Reactor": "袖珍核反应堆",
    "Powers drawn from dimensions we can't even see.": "从我们看不见的维度中汲取能量。",
    "+30% attack speed, +5000/sec passive": "+30%攻击速度，+5000/秒被动",
    "Harvested Star": "收获之星",
    "You plucked a star from the sky. Now it works for you.": "你从天上摘了一颗星。现在它对你有用了。",
    "+75% main ship damage, small AoE": "+75%主舰伤害，小范围AoE",
    "Singularity Cannon": "奇点大炮",
    "Contains a microscopic black hole. Totally safe.": "包含一个微观黑洞。完全安全。",
    "Cosmic Energy Battery": "宇宙能量电池",
    "Stores the energy of dying stars. Batteries not included.": "储存着垂死恒星的能量。电池不包括在内。",
    "[DAILY] Damage Dealer": "[日常] 伤害经销商",
    "Both click and fleet damage can crit for 1.4x damage": "点击和舰队伤害都可以造成1.4倍伤害的暴击",
    "Forbidden Theorems": "禁忌定理",
    "Knowledge that breaks minds. Very efficient.": "知识打破头脑。很能干的人。",
    "+50% auto-fire damage, ships learn from each other": "+50%的自动开火伤害，船只互相学习",
    "AI Swarm Intelligence": "AI群体智能",
    "The collective knows all. The collective destroys all.": "集体知道一切。集体毁灭一切。",
    "+0.0005× combo per level (total +0.001×)": "每级+0.0005×连击（合计+0.001×）",
    "+10% damage per level": "每级+10%伤害",
    "+15% points per level": "每级+15%点数",
    "+2% crit chance per level": "每级+2%暴击几率",
    "+20% boss damage per level": "每级增加20% boss伤害",
    "+20% XP per level": "每级+20%经验值",
    "+25% passive per level": "每级+25%被动",
    "+5% attack speed per level": "每级+5%攻击速度",
    "Ancient Wisdom": "上古智慧",
    "Auto-Buy Protocol": "自动购买协议",
    "Combo multiplier builds faster": "连击倍率构建更快",
    "Cosmic Fortune": "宇宙命运",
    "Deal extra damage to bosses": "对boss造成额外伤害",
    "Eternal Power": "永恒之力",
    "Head Start": "领先一步",
    "Idle Mastery": "放置精通",
    "Lucky Stars": "幸运之星",
    "Permanently increase all damage": "永久增加所有伤害",
    "Permanently increase attack speed": "永久提高攻击速度",
    "Permanently increase critical hit chance": "永久增加暴击几率",
    "Permanently increase passive generation": "永久增加被动产量",
    "Permanently increase point gains": "永久增加点数增益",
    "Permanently increase XP gains": "永久增加经验值收益",
    "Persistent Memory": "持久记忆",
    "REACH LEVEL 100 TO ASCEND (Current: 75)": "升到100级（当前等级：75）",
    "Retain +10% upgrades per level": "每级保留+10%的升级",
    "Retain a percentage of upgrade levels": "保留一定比例的升级级别",
    "Start +5 levels per level": "开始时每级+5级",
    "Start at a higher level after ascension": "提升后从更高的层次开始",
    "Time Dilation": "时间膨胀",
    "Unlock automatic purchase of affordable upgrades": "解锁自动购买可负担的升级",
    "Unlocks Auto-Buy feature": "解锁自动购买功能",
    ". Your mission: pop every single one of them. Build your fleet, upgrade your arsenal, \n              and turn this invasion into pure profit. The universe depends on your clicking skills! 🚀": "。你的任务是把他们一个个干掉。建立你的舰队，升级你的武器库，把这次入侵变成纯粹的利润。宇宙取决于你的点击技能！🚀",
    "Use the buy quantity selector (1x, 5x, 10x, MAX) to purchase multiple upgrades at once! \n              Auto-Buy can be unlocked in the Ascension Store for 50 Prestige Points. Good luck, Commander! 🚀": "使用购买数量选择器（1x, 5x, 10x， MAX）一次购买多个升级！自动购买可以在转生商店花费50声望点数解锁。祝你好运，指挥官！🚀",
    "🌌 The Invasion Begins...": "🌌 入侵开始了…",
    "🎮 Welcome to BOBBLE": "🎮 欢迎来到 泡泡入侵者",
    "💡 How to Play": "💡 游戏玩法",
    "💡 Pro Tip:": "💡 专业提示：",
    "Ascend for Power": "转生获得力量",
    "Buy Upgrades": "购买升级",
    "Click or tap anywhere to fire lasers from your fleet. Each click deals damage to the alien bubblewrap targets!": "点击或点击任何地方从你的舰队发射激光。每次点击都会对外星泡泡目标造成伤害！",
    "Click to Attack": "点击攻击",
    "Commander,": "指挥官,",
    "Complete daily and weekly missions to earn bonus rewards. Check the Missions tab to see your objectives!": "完成每日和每周任务获得奖励。检查任务标签，看看你的目标！",
    "Complete Missions": "完成任务",
    "Customize Your Fleet": "定制你的舰队",
    "Defeat Bosses": "击败Boss",
    "economically inconvenient": "经济上不方便",
    "Face massive bosses at regular intervals! Defeat them before time runs out to progress and unlock special rewards!": "定时面对大量boss ！在时间耗尽之前击败他们并解锁特殊奖励！",
    "Gityx游戏": "Gityx",
    "Purchase upgrades in the shop to increase damage, add ships, boost crit chance, and unlock powerful abilities!": "在商店购买升级，以增加伤害，增加船只，提高暴击率，并解锁强大的技能！",
    "Reach level 100 to ascend! Reset your progress but gain Prestige Points to unlock permanent bonuses!": "升到100级就可以转生！重置你的进度，但获得声望点解锁永久加成！",
    "Start Playing!": "开始游戏！",
    "these bubblewrap aliens have invaded our profit margins! They're not actually dangerous - just... ": "这些泡泡外星人已经侵占了我们的利润空间！它们其实并不危险，只是……",
    "Unlock and customize visual themes for your ships, lasers, particles, and background as you progress!": "随着你的进展，解锁和自定义可视化主题为你的船，激光，粒子和背景！",
    "– shielded core that shrugs off click damage.": "-屏蔽核心，摆脱点击伤害。",
    "– ultra-rare loot bubble that always drops a power-up.": "-超级稀有的战利品泡泡，总是掉落一个能量提升。",
    "#PopTheProfit • https://bobble-invaders.click/": "#PopTheProfit•https://bobble-invaders.click/",
    "⚙️ Gameplay Tweaks": "⚙️游戏调整",
    "⚡ Unspent Prestige Points Bonus:": "⚡ 未使用的声望点数奖励：",
    "✨ Broadcast on X (Twitter)": "✨ 在X上广播（Twitter）",
    "🌟 How Prestige Points Work:": "🌟 声望点数是如何工作的：",
    "🎨 UI & Feedback": "🎨 用户界面与反馈",
    "👾 New Enemy Archetypes": "👾 新敌人原型",
    "💡 Tip:": "💡 提示:",
    "📋 Copy Holo-Stats": "📋 复制全息统计",
    "🚀 Share Your Command Center": "🚀 分享你的指挥中心",
    "All special aliens now show a mini badge above their HP bar so you can react instantly.": "所有特殊的外星人现在在他们的HP条上方显示一个迷你徽章，所以你可以立即做出反应。",
    "Base PP:": "基础声望点数：",
    "Base:": "基础:",
    "Bonus PP:": "奖励声望点数：",
    "Bonus:": "奖励：",
    "Boost all per-hit damage (clicks and ships deal the same amplified damage).": "提高所有的每击伤害（点击和船只造成相同的放大伤害）。",
    "Boss hold warning now explains the 90% XP slowdown while you rematch.": "Boss保持警告现在解释90%的经验减慢当你重赛。",
    "Current Income Bonus:": "当前收入加成：",
    "Each": "每个",
    "Earn extra valuable Prestige Points by surpassing your previous best level!": "赚取额外的宝贵威望点，超过你以前的最佳水平！",
    "Enemy effect tags now use concise emoji labels in every language.": "敌人效果标签现在在每种语言中都使用简洁的表情符号标签。",
    "Guardian": "守护者",
    "Hoarder": "囤积者",
    "Hoarder spawn rate reduced 10× to keep guaranteed loot exciting.": "囤积者出生概率降低10倍，保证获得的战利品更加刺激。",
    "LIVE FLEET REPORT": "实时舰队报告",
    "Master the perfect critical hit. Only affects your clicks (fleet ships cannot crit). Maximum destruction efficiency. Very satisfying.": "掌握完美的暴击。只影响你的点击（舰队不能暴击）。最大的破坏效率。非常令人满意的。",
    "🆕 What's New in 1.10.0 (Beta)": "🆕1.10.0 （Beta版）新增功能",
    "Previous Best Level:": "之前最佳等级：",
    "Scout, Tank, Healer, Guardian, and Hoarder stats retuned for clearer identities.": "侦察兵，坦克，治疗者，守护者和囤积者的属性将会更加清晰。",
    "Simplified special-alien overlays to spotlight their mechanics.": "简化了特殊外星人的叠加，以突出他们的机制。",
    "This applies to clicks, kills, and passive generation.": "这适用于点击、击杀和被动生成。",
    "Tip: Drop this card into your Discord squad or socials to recruit more bubblewrap poppers.": "小贴士：将这张卡片放入你的Discord小队或社交组织中，以招募更多的气泡终结者。",
    "to all point sources!": "给所有点源！",
    "Total Gain:": "总增益:",
    "unspent Prestige Point gives +0.25% income": "未使用的声望点数给+0.25%的收入",
    "Version badge and splash updated to highlight the new feature set.": "版本徽章和splash更新，以突出显示新功能集。",
    "Watch the icon above an alien’s HP bar—pink sparkles mean free loot is guaranteed!": "观看外星人的HP条上面的图标-粉红色的闪光意味着免费的战利品是有保证的！",
    "You always earn Prestige Points for ascending past level 99!": "当你升到99级时，你总是可以获得声望点！",
    "Your latest BOBBLE feats, wrapped in a holographic stat card ready to flex anywhere.": "您最新的泡泡壮举，包裹在全息属性卡中随时可以在任何地方伸缩。",
    "- it makes your clicks even more powerful!": "- 它使您的点击更加强大！",
    "• Ascend at level 120+ to gain meaningful": "• 升到120级以上就能获得意义",
    "• Example: 100 combo = 1.05x damage, 500 combo = 1.25x damage": "• 例子：100连击 = 1.05倍伤害，500连击= 1.25倍伤害",
    "• Prestige upgrades provide strong, permanent bonuses—plan your runs": "• 声望升级提供强大的，永久的奖金-计划您的运行",
    "• Push for higher levels before ascending for bonus PP": "• 推动更高的级别，然后再转生，以获得额外的声望点数",
    "💡 Critical hits only work on your clicks - fleet ships cannot crit!": "💡暴击只对你的点击起作用 - 舰队不能暴击！",
    "💡 Stacks multiplicatively with Special Upgrade discounts!": "💡有特殊升级折扣，可成倍叠加！",
    "🔴 Tank (≈15%):": "🔴坦克（≈15%）：",
    "🟡 Scout (≈20%):": "🟡侦察兵（≈20%）：",
    "🟢 Healer (≈5%):": "🟢治疗者（≈5%）：",
    "Damage Per Ship (same as clicks):": "每艘船的伤害（与点击相同）：",
    "Each ship adds to your total DPS (same damage per hit as clicks)": "每艘船都会增加你的总每秒伤害(DPS)（每次命中的伤害与点击相同）",
    "Focus on clicking for combo scaling and crit damage": "专注于点击连击缩放和暴击伤害",
    "Increases both click AND fleet damage equally (1:1 ratio)": "同时增加点击和舰队伤害（1:1的比例）",
    "Only affects clicks - fleet ships cannot crit": "只影响点击-舰队不能暴击",
    "Only clicks can crit - fleet ships deal consistent damage": "只有点击可以暴击-舰队船只造成一致的伤害",
    "Standard HP and rewards": "标准生命值和奖励",
    "About +28% attack speed, +10000/sec passive": "大约+28%攻击速度，+10000/秒被动",
    "Both exists and doesn't exist. Both cheaper and more powerful.": "既存在又不存在。既便宜又强大。",
    "Schrödinger's Upgrade": "薛定谔的升级",
    "Siphon energy from the fabric of space.": "从空间结构中吸取能量。",
    "Vacuum Energy Tap": "真空能量开关",
    "Change the fundamental laws. Just a little.": "改变基本定律。只是一点点。",
    "Universal Constants Manipulator": "通用常数机械手",
    "🟢 Normal (≈60%):": "",
    "50% HP, 2× speed, 70% size, 1.5× points": "",
    "Each ship fires 1.41 times per second, dealing 892.7 per hit (same damage as clicks, but cannot crit)": "",
    "3, Ships gain about +14% attack speed": "3，舰船的攻击速度增加14%",
    "About +9% attack speed, chain lightning": "大约+9%攻击速度，连锁闪电",
    "Aliens confused, +15% all stats, +5% attack speed": "外星人迷惑，+15%所有属性，+5%攻击速度",
    "All ships gain about +40% attack speed": "所有船只获得+40%攻击速度",
    "All stats +40%, ships fire about +20% faster": "所有属性+40%，飞船发射速度+20%",
    "Ship fire cooldown reduced by ~14%": "船火冷却时间降低14%",
    "You must defeat it to progress. XP gains are reduced by 90% until victory.": "必须击败它才能继续前进。胜利之前，经验增益降低90%。",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "PP": "声望点数",
    // 图标代码，不能汉化
    "Jacorb's Games": "Jacorb's Games",
    "Ctrl + M": "Ctrl + M",
    "Ctrl + D": "Ctrl + D",
    "×": "×",
    "⏱️": "⏱️",
    "⚔️": "⚔️",
    "◀": "◀",
    "🎨": "🎨",
    "☰": "☰",
    "⚙️": "⚙️",
    "⚠️": "⚠️",
    "⚡": "⚡",
    "🛸": "🛸",
    "🔥": "🔥",
    "🔒": "🔒",
    "📖": "📖",
    "📊": "📊",
    "💫": "💫",
    "👻": "👻",
    "👾": "👾",
    "🌌": "🌌",
    "🌟": "🌟",
    "✓": "✓",
    "✕": "✕",
    "✨": "✨",
    "🎯": "🎯",
    "🏆": "🏆",
    "--": "--",
    "🚀": "🚀",
    "⌚": "⌚",
    "⏰": "⏰",
    "☕": "☕",
    "☠️": "☠️",
    "♾️": "♾️",
    "⚖️": "⚖️",
    "⚛️": "⚛️",
    "⚫": "⚫",
    "⛈️": "⛈️",
    "⭐": "⭐",
    "🌀": "🌀",
    "🌐": "🌐",
    "🌑": "🌑",
    "🌠": "🌠",
    "🌩️": "🌩️",
    "🌪️": "🌪️",
    "🎖️": "🎖️",
    "🏦": "🏦",
    "🏭": "🏭",
    "🏰": "🏰",
    "🐉": "🐉",
    "👁️": "👁️",
    "👆": "👆",
    "👑": "👑",
    "👹": "👹",
    "💀": "💀",
    "💍": "💍",
    "💎": "💎",
    "💠": "💠",
    "💡": "💡",
    "💥": "💥",
    "💨": "💨",
    "💪": "💪",
    "💰": "💰",
    "💵": "💵",
    "📅": "📅",
    "📚": "📚",
    "📡": "📡",
    "🔆": "🔆",
    "🔋": "🔋",
    "🔧": "🔧",
    "🔨": "🔨",
    "🔩": "🔩",
    "🔬": "🔬",
    "🔭": "🔭",
    "🔮": "🔮",
    "🔱": "🔱",
    "🕐": "🕐",
    "🕰️": "🕰️",
    "🕳️": "🕳️",
    "🖱️": "🖱️",
    "🤑": "🤑",
    "🤖": "🤖",
    "🥚": "🥚",
    "🧘": "🧘",
    "🧠": "🧠",
    "🚁": "🚁",
    "🛠️": "🛠️",
    "🛰️": "🛰️",
    "💥": "💥",
    "???": "???",
    "S:": "S:",
    "P:": "P:",
    "A:": "A:",
    "H:": "H:",
    "I:": "I:",
    "M:": "M:",
    "Ctrl + F1:": "Ctrl + F1:",
    "Ctrl + F1:": "",
    "Ctrl + M:": "Ctrl + M:",
    "🌈": "🌈",
    "•": "•",
    "♻️": "♻️",
    "4️⃣2️⃣": "4️⃣2️⃣",
    "🐝": "🐝",
    "🎲": "🎲",
    "🍕": "🍕",
    "📋": "📋",
    "🦆": "🦆",
    "🍀": "🍀",
    "🪩": "🪩",
    "🎮": "🎮",
    "🗿": "🗿",
    "🗺️": "🗺️",
    "☢️": "☢️",
    "💚": "💚",
    "🕹️": "🕹️",
    "🛒": "🛒",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "+": "+",
    ".": ".",
    "…": "…",
    ":": ":",
    "-": "-",
    "|": "|",
    "(": "(",
    ")": ")",
    "Scientific": "科学计数法",
    "Standard": "标准",
    "Blind": "盲文",
    "Letters": "字母",
    "Mixed Engineering": "混合工程",
    "Mixed Scientific": "混合科学",
    "Chemistry": "化学",
    "Engineering": "工程符号",
    "By Jacorb90": "By Jacorb90",
    "content_copy": "content_copy",
    "library_books": "library_books",
    "discord": "discord",
    "drag_handle": "drag_handle",
    "edit": "edit",
    "forum": "forum",
    "content_paste": "content_paste",
    "delete": "delete",
    "info": "info",
    "settings": "settings",
    'Twitter': 'Twitter',
    "Discord": "Discord",
    "Facebook": "Facebook",
    "Instagram": "Instagram",
    "gityxcom": "gityxcom",
    "Footer": "Footer",
    "Wiki": "Wiki",
    "gityx": "gityx",

    //树游戏
    'Loading...': '加载中...',
    'ALWAYS': '一直',
    'HARD RESET': '硬重置',
    'Export to clipboard': '导出到剪切板',
    'INCOMPLETE': '不完整',
    'HIDDEN': '隐藏',
    'AUTOMATION': '自动',
    'NEVER': '从不',
    'ON': '打开',
    'OFF': '关闭',
    'SHOWN': '显示',
    'Play Again': '再次游戏',
    'Keep Going': '继续',
    'The Modding Tree Discord': '模型树Discord',
    'You have': '你有',
    'It took you {{formatTime(player.timePlayed)}} to beat the game.': '花费了 {{formatTime(player.timePlayed)}} 时间去通关游戏.',
    'Congratulations! You have reached the end and beaten this game, but for now...': '恭喜你！ 您已经结束并通关了本游戏，但就目前而言...',
    'Main Prestige Tree server': '主声望树服务器',
    'Reach {{formatWhole(ENDGAME)}} to beat the game!': '达到 {{formatWhole(ENDGAME)}} 去通关游戏!',
    "Loading... (If this takes too long it means there was a serious error!": "正在加载...（如果这花费的时间太长，则表示存在严重错误！",
    'Loading... (If this takes too long it means there was a serious error!)←': '正在加载...（如果时间太长，则表示存在严重错误！）←',
    'Main\n\t\t\t\tPrestige Tree server': '主\n\t\t\t\t声望树服务器',
    'The Modding Tree\n\t\t\t\t\t\t\tDiscord': '模型树\n\t\t\t\t\t\t\tDiscord',
    'Please check the Discord to see if there are new content updates!': '请检查 Discord 以查看是否有新的内容更新！',
    'aqua': '水色',
    'AUTOMATION, INCOMPLETE': '自动化，不完整',
    'LAST, AUTO, INCOMPLETE': '最后，自动，不完整',
    'NONE': '无',
    'P: Reset for': 'P: 重置获得',
    'Git游戏': 'Git游戏',
    'QQ群号': 'QQ群号',
    'x': 'x',
    'QQ群号:': 'QQ群号:',
    '* 启用后台游戏': '* 启用后台游戏',
    '更多同类游戏:': '更多同类游戏:',
    'i': 'i',
    'I': 'I',
    'II': 'II',
    'III': 'III',
    'IV': 'IV',
    'V': 'V',
    'VI': 'VI',
    'VII': 'VII',
    'VIII': 'VIII',
    'X': 'X',
    'XI': 'XI',
    'XII': 'XII',
    'XIII': 'XIII',
    'XIV': 'XIV',
    'XV': 'XV',
    'XVI': 'XVI',
    'A': 'A',
    'B': 'B',
    'C': 'C',
    'D': 'D',
    'E': 'E',
    'F': 'F',
    'G': 'G',
    'H': 'H',
    'I': 'I',
    'J': 'J',
    'K': 'K',
    'L': 'L',
    'M': 'M',
    'N': 'N',
    'O': 'O',
    'P': 'P',
    'Q': 'Q',
    'R': 'R',
    'S': 'S',
    'T': 'T',
    'U': 'U',
    'V': 'V',
    'W': 'W',
    'X': 'X',
    'Y': 'Y',
    'Z': 'Z',
    'a': 'a',
    'b': 'b',
    'c': 'c',
    'd': 'd',
    'e': 'e',
    'f': 'f',
    'g': 'g',
    'h': 'h',
    'i': 'i',
    'j': 'j',
    'k': 'k',
    'l': 'l',
    'm': 'm',
    'n': 'n',
    'o': 'o',
    'p': 'p',
    'q': 'q',
    'r': 'r',
    's': 's',
    't': 't',
    'u': 'u',
    'v': 'v',
    'w': 'w',
    'x': 'x',
    'y': 'y',
    'z': 'z',
    '<': '<',
    '<<': '<<',
    '>': '>',
    '>>': '>>',
    'Jan': '1月',
    'Feb': '2月',
    'Mar': '3月',
    'Apr': '4月',
    'May': '5月',
    'Jun': '6月',
    'Jul': '7月',
    'Aug': '8月',
    'Sep': '9月',
    'Oct': '10月',
    'Nov': '11月',
    'Dec': '12月',
    '': '',
    '': '',
    '': '',
    '': '',
    '': '',

}


//需处理的前缀，此处可以截取语句开头部分的内容进行汉化
//例如：Coin: 13、Coin: 14、Coin: 15... 这种有相同开头的语句
//可以在这里汉化开头："Coin: ":"金币: "
var cnPrefix = {
    "\n": "\n",
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    //树游戏
    "\t\t\t": "\t\t\t",
    "\n\n\t\t": "\n\n\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "Show Milestones: ": "显示里程碑：",
    "Autosave: ": "自动保存: ",
    "Offline Prod: ": "离线生产: ",
    "Completed Challenges: ": "完成的挑战: ",
    "High-Quality Tree: ": "高质量树贴图: ",
    "Offline Time: ": "离线时间: ",
    "Theme: ": "主题: ",
    "Anti-Epilepsy Mode: ": "抗癫痫模式：",
    "In-line Exponent: ": "直列指数：",
    "Single-Tab Mode: ": "单标签模式：",
    "Time Played: ": "已玩时长：",
    "Shift-Click to Toggle Tooltips: ": "Shift-单击以切换工具提示：",
    "Notation: ": "符号: ",
    "Toggle Music: ": "切换声音: ",
    "Animations: ": "动画: ",
    "Current Endgame: ": "当前终局: ",
    "Space Background: ": "太空背景: ",
    "Cost: ": "成本: ",
    "⚔️ DPS: ": "⚔️ 每秒伤害: ",
    "💰 /sec: ": "💰 /秒: ",
    "💰 Total Income: ": "💰 总收入: ",
    "Points: ": "点数: ",
    "✨ Crit: ": "✨ 暴击: ",
    "🏭 Passive: ": "🏭 被动: ",
    "Fleet: ": "舰队: ",
    "Reach Attack Speed level ": "达到攻击速度等级 ",
    "Reach Critical Strike level ": "暴击 达到 等级 ",
    "Reach Damage Amplifier level ": "伤害放大器 达到 等级 ",
    "Reach Passive Income Core level ": "被动收入 达到 等级 ",
    "Reach Knowledge Core level ": "知识核心 达到 等级 ",
    "Lv.": "等级",
    "✅ ⚡ Power-Up Spawned: ": "✅ ⚡ 通电产生: ",
    "[DAILY] ": "[日常] ",
    "[DAILY] ": "[日常] ",
    "Passive point generation +": "被动点数生成 +",
    "🎯 🎯 Mission Complete: ": "🎯 🎯 任务完成: ",
    "Reach Passive Income level ": "达到被动收入等级 ",
    "XP gain +": "经验值增益 +",
    "Passive generation +": "被动生成 +",
    "Passive generation x": "被动生成 x",
    "Upgrades unlocked: ": "解锁升级：",
    "Aliens popped: ": "外星人死亡：",
    "Bosses crushed: ": "击杀Boss：",
    "Playtime logged: ": "游戏时间：",
    "Points banked: ": "存储点数：",
    " (same damage as clicks, but cannot crit)": "（与点击相同，但不能暴击）",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需处理的后缀，此处可以截取语句结尾部分的内容进行汉化
//例如：13 Coin、14 Coin、15 Coin... 这种有相同结尾的语句
//可以在这里汉化结尾：" Coin":" 金币"
var cnPostfix = {
    "                   ": "                   ",
    "                  ": "                  ",
    "                 ": "                 ",
    "                ": "                ",
    "               ": "               ",
    "              ": "              ",
    "             ": "             ",
    "            ": "            ",
    "           ": "           ",
    "          ": "          ",
    "         ": "         ",
    "        ": "        ",
    "       ": "       ",
    "      ": "      ",
    "     ": "     ",
    "    ": "    ",
    "   ": "   ",
    "  ": "  ",
    " ": " ",
    "\n": "\n",
    "\n\t\t\t": "\n\t\t\t",
    "\t\t\n\t\t": "\t\t\n\t\t",
    "\t\t\t\t": "\t\t\t\t",
    "\n\t\t": "\n\t\t",
    "\t": "\t",
    "/sec)": "/秒)",
    ' I': ' I',
    ' II': ' II',
    ' III': ' III',
    ' IV': ' IV',
    ' V': ' V',
    ' VI': ' VI',
    ' VII': ' VII',
    ' VIII': ' VIII',
    ' X': ' X',
    ' XI': ' XI',
    ' XII': ' XII',
    ' XIII': ' XIII',
    ' XIV': ' XIV',
    ' XV': ' XV',
    ' XVI': ' XVI',
    "/sec": "/秒",
    "% XP)": "% 经验值)",
    "/hit)": "/攻击)",
    " ships)": " 飞船)",
    "% to ALL costs": "% 到全部成本",
    "% to SHIP upgrade costs only": "% 仅到飞船升级成本",
    "% speed)": "% 速度)",
    "% damage)": "% 伤害)",
    "% costs)": "% 成本)",
    "% fleet dmg)": "% 舰队伤害)",
    "% all dmg)": "% 所有伤害)",
    "/hit ⚔️)": "/攻击 ⚔️)",
    "": "",
    "": "",
    "": "",
    "": "",
    "": "",
}

//需排除的，正则匹配
var cnExcludeWhole = [
    /^(\d+)$/,
    /^\s*$/, //纯空格
    /^([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)h$/,
    /^([\d\.]+)m$/,
    /^([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h ([\d\.]+)m ([\d\.]+)s$/,
    /^([\d\.]+)y ([\d\.]+)d ([\d\.]+)h$/,
    /^([\d\.]+)\-([\d\.]+)\-([\d\.]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)$/,
    /^×([\d\.]+)$/,
    /^x([\d\.]+)$/,
    /^v([\d\.]+)$/,
    /^\$([\d\.]+)$/,
    /^\(([\d\.]+)\)$/,
    /^([\d\.]+)\%$/,
    /^\+([\d\.]+)\%$/,
    /^([\d\.]+)\/([\d\.]+)$/,
    /^([\d\.]+)\/([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.,]+)$/,
    /^\(([\d\.]+)\/([\d\.]+)\)$/,
    /^成本(.+)$/,
    /^\(([\d\.]+)\%\)$/,
    /^([\d\.]+):([\d\.]+):([\d\.]+)$/,
    /^([\d\.]+)K$/,
    /^\$ ([\d\.]+)K$/,
    /^\$ ([\d\.]+)M$/,
    /^\$ ([\d\.]+)B$/,
    /^\$ ([\d\.]+)T$/,
    /^([\d\.]+)M$/,
    /^\+([\d\.]+)M$/,
    /^([\d\.]+)M \(x([\d\.]+)\)$/,
    /^([\d\.]+)B$/,
    /^([\d\.]+) K$/,
    /^([\d\.]+) M$/,
    /^([\d\.]+) B$/,
    /^([\d\.]+) T$/,
    /^([\d\.]+) Qi$/,
    /^([\d\.]+) Qa$/,
    /^([\d\.]+) Sp$/,
    /^([\d\.]+) Oc$/,
    /^([\d\.]+) Dc$/,
    /^([\d\.]+) UDc$/,
    /^([\d\.]+) No$/,
    /^([\d\.]+) Sx$/,
    /^([\d\.]+) QaDc$/,
    /^([\d\.]+)s$/,
    /^([\d\.]+)x$/,
    /^([\d\.]+)x \(\+([\d\.]+)\%\)$/,
    /^x([\d\.]+)$/,
    /^([\d\.]+) \/ ([\d\.]+) \(([\d\.]+)\%\)$/,
    /^([\d\.]+) \(([\d\.]+)ms\)$/,
    /^([\d\.]+) \(([\d\.]+)\%\)$/,
    /^([\d\.]+) \(([\d\.]+)$/,
    /^([\d\.]+)K \(([\d\.]+)$/,
    /^([\d\.]+)M \(([\d\.]+)$/,
    /^([\d\.]+)B \(([\d\.]+)$/,
    /^([\d\.]+)T \(([\d\.]+)$/,
    /^([\d\.]+) \(([\d\.]+)(.+)$/,
    /^([\d\.]+) \(\+([\d\.]+)$/,
    /^([\d\.]+) \(\-([\d\.]+)$/,
    /^([\d\.,]+)$/,
    /^\$([\d\.,]+)$/,
    /^\+([\d\.,]+)$/,
    /^\/([\d\.,]+)$/,
    /^🚀 \+([\d\.,]+)$/,
    /^\-([\d\.,]+)$/,
    /^([\d\.,]+)x$/,
    /^x([\d\.,]+)$/,
    /^×([\d\.,]+)$/,
    /^\$ ([\d\.,]+)$/,
    /^\$ \+([\d\.,]+)$/,
    /^([\d\.,]+) \/ ([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+) \/ ([\d\.]+)e([\d\.,]+)$/,
    /^\$([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)\/([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e\+([\d\.,]+)$/,
    /^e([\d\.]+)e([\d\.,]+)$/,
    /^x([\d\.]+)e([\d\.,]+)$/,
    /^([\d\.]+)e([\d\.,]+)x$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])|[\u21A9\u21AA\u25B6\u25C0\u2B06\u2B07\u2B05\u2B95\u2B99\u2B9A]+$/,
    // /^([\uD800-\uDBFF][\uDC00-\uDFFF])|([\u2600-\u27BF])|([\u2300-\u23FF])|([\u2B50-\u2B55])|([\u203C-\u3299])+$/,
    // /^[\uD800-\uFFFF]+$/,
    /^[\u4E00-\u9FA5]+$/
];
var cnExcludePostfix = [
]

//正则替换，带数字的固定格式句子
//纯数字：(\d+)
//字母加数字：([\d\.]+[A-Za-z])
//逗号：([\d\.,]+)
//小数点：([\d\.]+)
//原样输出的字段：(.+)
//换行加空格：\n(.+)
//&nbsp;空格：\xA0
var cnRegReplace = new Map([
    [/^([\d\.]+) hours ([\d\.]+) minutes ([\d\.]+) seconds$/, '$1 小时 $2 分钟 $3 秒'],
    [/^You are gaining (.+) elves per second$/, '你每秒获得 $1 精灵'],
    [/^You have (.+) points$/, '你有 $1 点数'],
    [/^Next at (.+) points$/, '下一个在 $1 点数'],
    [/^About (.+) attack speed, (.+)\/sec passive$/, '大约 $1 攻击速度，$2/秒被动'],
    [/^Ships gain about (.+) attack speed$/, '飞船获得大约 $1 的攻击速度'],
    [/^Ships fire about (.+) faster$/, '飞船开火速度提升大约 $1'],
    [/^Ships fire about (.+) faster, Damage (.+)$/, '飞船开火速度提升大约 $1, 伤害 $2'],
    [/^All damage (.+), Attack speed (.+)$/, '所有伤害 $1, 攻击速度 $2'],
    [/^Achieve a (.+)x combo$/, '完成 $1x 连击'],
    [/^Level (.+) • (.+) ships deployed$/, '$1 级 • 已部署 $2 飞船'],
    [/^Your clicks always hit and deal (.+) damage$/, '你的点击总是命中并造成 $1 伤害'],
    [/^Your clicks always hit and deal (.+) damage \(can crit for (.+)x\)$/, '你的点击总是命中并造成 $1 伤害 (可以暴击到 $2x)'],
    [/^Each ship fires (.+) times per second, dealing (.+) per hit$/, '每艘飞船每秒发射 $1 次，每次击中造成 $2 伤害'],
    [/^Jan ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 1 月 $1, $3:$4'],
    [/^Feb ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 2 月 $1, $3:$4'],
    [/^Mar ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 3 月 $1, $3:$4'],
    [/^Apr ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 4 月 $1, $3:$4'],
    [/^May ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 5 月 $1, $3:$4'],
    [/^Jun ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 6 月 $1, $3:$4'],
    [/^Jul ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 7 月 $1, $3:$4'],
    [/^Aug ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 8 月 $1, $3:$4'],
    [/^Sep ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 9 月 $1, $3:$4'],
    [/^Oct ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 10 月 $1, $3:$4'],
    [/^Nov ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 11 月 $1, $3:$4'],
    [/^Dec ([\d\.,]+) ([\d\.,]+), ([\d\.,]+):([\d\.,]+)$/, '$2 年 12 月 $1, $3:$4'],
    [/^([\d\.]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+)\/sec$/, '$1\/秒'],
    [/^([\d\.,]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+) OOMs\/sec$/, '$1 OOMs\/秒'],
    [/^([\d\.]+)e([\d\.,]+)\/sec$/, '$1e$2\/秒'],
    [/^requires ([\d\.]+) more research points$/, '需要$1个研究点'],
    [/^([\d\.]+)e([\d\.,]+) points$/, '$1e$2 点数'],
    [/^([\d\.]+) elves$/, '$1 精灵'],
    [/^([\d\.]+)x HP, ([\d\.]+)x speed, ([\d\.]+)\% size, ([\d\.]+)x points$/, '$1x 生命值, $2x 速度, $3% 尺寸, $4x 点数'],
    [/^([\d\.]+)× HP, ([\d\.]+)× speed, ([\d\.]+)\% size, ([\d\.]+)× points$/, '$1x 生命值, $2x 速度, $3% 尺寸, $4x 点数'],
    [/^([\d\.]+)\% HP, ([\d\.]+)x speed, ([\d\.]+)\% size, ([\d\.]+)x points$/, '$1% 生命值, $2x 速度, $3% 尺寸, $4x 点数'],
    [/^([\d\.]+)\% HP, ([\d\.]+)x speed, ([\d\.]+)\% regenerates, ([\d\.]+)x points$/, '$1% 生命值, $2x 速度, $3% 恢复率, $4x 点数'],
    [/^([\d\.]+)\% HP, ([\d\.]+)\% speed, regenerates, ([\d\.]+)× points$/, '$1% 生命值, $2x 速度, $3% 恢复率, $4x 点数'],
    [/^([\d\.]+)\% HP, ([\d\.]+)\% speed, regenerates, ([\d\.]+)x points$/, '$1% 生命值, $2% 速度, 恢复率, $3x 点数'],
    [/^([\d\.]+) \+ \(combo × ([\d\.]+)\)$/, '$1 + (连击 × $2)'],
    [/^([\d\.]+) shots$/, '$1 射击'],
    [/^([\d\.]+)x damage$/, '$1x 伤害'],
    [/^([\d\.]+)x XP$/, '$1x 经验值'],
    [/^Release Beta ([\d\.]+)$/, '发行测试版 $1'],
    [/^([\d\.]+)d ([\d\.]+)h ([\d\.]+)m$/, '$1天 $2小时 $3分'],
    [/^([\d\.]+)e([\d\.,]+) elves$/, '$1e$2 精灵'],
    [/^([\d\.,]+) PP$/, '$1 声望点数'],
    [/^([\d\.,]+) elves$/, '$1 精灵'],
    [/^([\d\.,]+)h ([\d\.,]+)m$/, '$1小时 $2分钟'],
    [/^([\d\.,]+) Prestige Points$/, '$1 声望点数'],
    [/^([\d\.,]+)x Normal$/, '$1x 正常'],
    [/^([\d\.,]+)x Speed$/, '$1x 速度'],
    [/^\+([\d\.,]+) Boss Kills$/, '+$1 Boss击杀'],
    [/^\+([\d\.,]+)(.+) Clicks$/, '+$1$2 点击'],
    [/^\+([\d\.,]+)(.+) Points$/, '+$1$2 点数'],
    [/^\+([\d\.,]+) Ships$/, '+$1 飞船'],
    [/^\+([\d\.,]+) Levels$/, '+$1 等级'],
    [/^⭐ \+([\d\.,]+) XP$/, '⭐ +$1 经验值'],
    [/^Reach prestige ([\d\.,]+)$/, '达到声望 $1'],
    [/^Reach level ([\d\.,]+)$/, '达到等级 $1'],
    [/^TIME: ([\d\.,]+)s$/, '时间: $1秒'],
    [/^Level ([\d\.,]+)$/, '等级 $1'],
    [/^BUY x([\d\.,]+)$/, '购买 x$1'],
    [/^Day ([\d\.,]+)$/, '天数 $1'],
    [/^Have all main upgrades at level ([\d\.,]+) or higher$/, '所有主要升级达到 $1 或更高'],
    [/^Deal ([\d\.,]+) total damage$/, '总计造成 $1 伤害'],
    [/^Defeat ([\d\.,]+) bosses$/, '击败 $1 Boss'],
    [/^Accumulate ([\d\.,]+) points$/, '积累 $1 点数'],
    [/^Command ([\d\.,]+) ships$/, '命令 $1 飞船'],
    [/^Unlock ([\d\.,]+) special technologies$/, '解锁 $1 特殊技术'],
    [/^Land ([\d\.,]+) critical hits$/, '造成 $1 暴击'],
    [/^Click ([\d\.,]+) times$/, '点击 $1 次'],
    [/^Destroy ([\d\.,]+) aliens$/, '消灭 $1 外星人'],
    [/^Purchase ([\d\.,]+) upgrades$/, '购买 $1 升级'],
    [/^Play for ([\d\.,]+) minutes$/, '玩游戏 $1 分钟'],
    [/^Play for ([\d\.,]+) hour$/, '玩游戏 $1 小时'],
    [/^Play for ([\d\.,]+) hours$/, '玩游戏 $1 小时'],
    [/^Play for ([\d\.,]+) hours \(total\)$/, '玩游戏 $1 小时 (总计)'],
    [/^level ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^Level: ([\d\.,]+) \/ ([\d\.,]+)$/, '等级 $1 \/ $2'],
    [/^\*(.+) to electricity gain$/, '\*$1 到电力增益'],
    [/^(.+)→ Every (.+) levels \((.+)\): (.+), etc.$/, '$1→ 每 $2 级 ($3): $4, 等等.'],
    [/^(.+)→ Every (.+) levels \((.+)\): (.+)$/, '$1→ 每 $2 级 ($3): $4, 等等.'],
    [/^(.+) all costs, (.+) XP$/, '$1 所有成本，$2 经验'],
    [/^Cost: (.+) points$/, '成本：$1 点数'],
    [/^Req: (.+) elves$/, '要求：$1 精灵'],
    [/^Req: (.+) \/ (.+) elves$/, '要求：$1 \/ $2 精灵'],
    [/^Usages: (\d+)\/$/, '用途：$1\/'],
    [/^workers: (\d+)\/$/, '工人：$1\/'],

]);